from abc import ABC, abstractmethod
from src.core.state import ResearchState, Hypothesis

class BaseScout(ABC):
    """Base class for all Scout agents."""
    
    name: str = "BaseScout"
    consumes_rasm: bool = True
    consumes_tashkeel: bool = False
    
    def run(self, state: ResearchState) -> ResearchState:
        """Standard run method that calls analyze and appends to raw_hypotheses."""
        hypotheses = self.analyze(state)
        
        # Validate each hypothesis has non-empty goal_link
        for h in hypotheses:
            if not h.goal_link.strip():
                raise ValueError(f"{self.name} produced hypothesis with empty goal_link")
        
        # Append to raw_hypotheses
        raw_hypotheses = state.get("raw_hypotheses", [])
        raw_hypotheses.extend(hypotheses)
        state["raw_hypotheses"] = raw_hypotheses
        
        return state
    
    @abstractmethod
    def analyze(self, state: ResearchState) -> list[Hypothesis]:
        """Analyze the data and return hypotheses. Must be implemented by subclasses."""
        pass
from abc import ABC, abstractmethod
from src.core.state import ResearchState, Hypothesis

class BaseScout(ABC):
    """
    Base class for all Scout agents in the Muqattaat Cryptanalytic Lab.
    
    Each Scout specializes in a specific type of pattern analysis:
    - Rasm scouts analyze skeletal letter sequences
    - Tashkeel scouts analyze diacritic patterns
    """
    
    name: str = "BaseScout"
    consumes_rasm: bool = False
    consumes_tashkeel: bool = False
    
    def run(self, state: ResearchState) -> ResearchState:
        """
        Main entry point for Scout execution.
        Calls analyze() and appends results to raw_hypotheses.
        """
        hypotheses = self.analyze(state)
        
        # Append to raw_hypotheses (don't overwrite)
        raw_hypotheses = state.get("raw_hypotheses", [])
        raw_hypotheses.extend(hypotheses)
        state["raw_hypotheses"] = raw_hypotheses
        
        return state
    
    @abstractmethod
    def analyze(self, state: ResearchState) -> list[Hypothesis]:
        """
        Analyze the research state and generate hypotheses.
        
        Args:
            state: Current research state containing matrices and data
            
        Returns:
            List of hypotheses generated by this scout
        """
        pass
